language: android

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

jdk:
  - oraclejdk8

android:
  components:
#    - platform-tools
#    - tools

    - build-tools-26.0.3
    - android-26

    - extra-android-m2repository # Android Support Repository
    - extra-android-support # Support Library

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-19
    - sys-img-x86-android-17

before_install:
  - yes | sdkmanager "platforms;android-27"

script:
  - ./gradlew clean build

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle